apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- if .Values.configmap }}
  config.yaml:
      {{- toYaml .Values.configmap . | indent 6 }}
  {{- end }}
