apiVersion: v2
name: producer
description: The producer chart for Kubernetes
type: application
version: 0.0.0
appVersion: 0.0.0
dependencies:
  - name: kafka
    version: 9.0.2
    repository: "@bitnami"
