name: Build Go

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.13.1"

      - run: go vet

  build:
    if: github.event_name == 'push'
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install @semantic-release/git @semantic-release/changelog @semantic-release/exec

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --ci

      - name: Set env variables
        run: |
          echo "::set-env name=user::$(echo ${{ github.repository }} | cut -d/ -f1)"; \
          echo "::set-env name=lowercase_user::$(echo ${{ github.repository }} | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')"; \
          echo "::set-env name=project::$(echo ${{ github.repository }} | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')"

      - name: Build the Docker image
        id: build
        run: docker build -t docker.pkg.github.com/$lowercase_user/$project/$project:latest -t docker.pkg.github.com/$lowercase_user/$project/$project:${{ steps.release.outputs.version }} --build-arg VERSION=${{ steps.release.outputs.version }} .

      - name: Docker login
        run: docker login docker.pkg.github.com -u $user -p ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to CR
        run: |
          docker push "docker.pkg.github.com/$lowercase_user/$project/$project:latest"; \
          docker push "docker.pkg.github.com/$lowercase_user/$project/$project:${{ steps.release.outputs.version }}"

      - name: Setup helm
        uses: azure/setup-helm@v1

      - name: Package helm
        run: |
          git clone https://$user:${{ secrets.token }}@github.com/$user/helm-chart.git ../helm-chart; \
          helm lint ./charts; \
          helm package --app-version ${{ steps.release.outputs.version }} --version ${{ steps.release.outputs.version }} ./charts; \
          helm repo index --url https://$(lowercase_user).github.io/helm-chart/ --merge ../helm-chart/index.yaml .; \
          mv index.yaml $project-*.tgz ../helm-chart/; \
          cd ../helm-chart && git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"; \
          git add . && git commit -m "Update $project helm chart" && git push origin master
